repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.2
  hooks:
    - id: ruff
      name: "Run Ruff Python linting"
    - id: ruff-format
      name: "Run Ruff Python formatting"
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
    - id: codespell
      name: "Check code for common misspellings"
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
    - id: mypy
      name: "MyPy Static type checks"
      additional_dependencies:
        - types-requests
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.7
  hooks:
    - id: clang-format
      name: "Clang C++ formatting"
      types_or: [c++, c, cuda]
- repo: local
  hooks:
    - id: cppcheck
      name: "C++ static analysis"
      types_or: [c++, c, cuda]
      entry: cppcheck -q -j8 --error-exitcode=1
      language: python
      additional_dependencies: ["cppcheck==1.5.1"]
      args:
        - --check-level=exhaustive
        - --language=c++
        - --enable=warning
        - --library=boost
        - -I include
        - src
        - test
        - torch_geopooling
