[build-system]
requires = [
    "torch >= 2.0.0+cpu, < 3.0.0+cpu; sys_platform == 'linux'",
    "torch >= 2.0.0, < 3.0.0; sys_platform == 'darwin' or sys_platform == 'win'",
    "cibuildwheel == 2.17.0",
    "numpy >= 1.4.0",
    "pybind11 >= 2.0.0, < 3.0.0",
    "pytest >= 8.0.0",
    "setuptools ~= 69.5.1",
    "sympy >= 1.12",
    "typing-extensions >= 4.11.0",
    "wheel >= 0.43.0"
]

build-backend = "setuptools.build_meta"
