name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install third-party libraries
      run: |
        apt-get update
        apt-get install -y libunwind-dev --no-install-recommends
        apt-get install -y cmake build-essential libboost-test-dev libfmt-dev --no-install-recommends

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: make test ARGS=--verbose"
