name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install third-party libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libunwind-dev --no-install-recommends
        sudo apt-get install -y libboost-test-dev libfmt-dev libtorch-dev --no-install-recommends

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: make test ARGS=--verbose"
