name: Pre-Commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:24.04
      options: --user root
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Configure apt to disable recommendations installation
      id: configure_apt
      run: |
        echo 'APT::Install-Recommends "false";' >> /etc/apt/apt.conf
        echo 'APT::Install-Suggests "false";' >> /etc/apt/apt.conf

    - name: Install third-party libraries and tools
      id: install_packages
      run: |
        apt-get update
        apt-get install -y cmake git build-essential libboost-test-dev libfmt-dev wget unzip
        apt-get install -y python3-numpy pre-commit

    - name: Fix git safe directory
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure --color=always
