name: Python Build Wheel

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0

      - uses: actions/upload-artifact@v4
        with:
          # Use a generated name, since upload-artifacts cannot upload files as is,
          # and running jobs in matrix result in a artifact name clash.
          name: python-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          retention-days: 7

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          pattern: python-wheels-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          # repository_url: https://test.pypi.org/legacy/
